### ISSUE TITLE
Issues with multiple rounds chat of model "omost-phi-3-mini-128k"

### ISSUE THREAD

**Issue by wikeeyang** [lllyasviel/Omost#40]
good idea and project! 
but I test on "omost-phi-3-mini-128k", and "SG161222/RealVisXL_V4.0", env as below:
windows 11 x64, Python 3.11.9, torch 2.3.0 + cu121, 24GB GPU and other recommand requirements.
single round prompt is correctly, but second round chat base our's sample, LLM append some error generate as below:
![2024-06-03_150149](https://github.com/lllyasviel/Omost/assets/131220899/50402db7-f2d8-4d1f-9142-9762e980a68c)

click "New Chat", only play sample prompt, the error occur again as below:
![2024-06-03_152223](https://github.com/lllyasviel/Omost/assets/131220899/6fa75fda-0cc9-475c-b53f-d5e287e09aa9)

the command windows's log as below:

D:\AITest\Omost\lib_omost\pipeline.py:64: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  alphas_cumprod = torch.tensor(np.cumprod(alphas, axis=0), dtype=torch.float32)
configuration_phi3.py: 10.4kB [00:00, 1.04MB/s]
A new version of the following files was downloaded from https://huggingface.co/microsoft/Phi-3-mini-128k-instruct:
- configuration_phi3.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
modeling_phi3.py: 73.8kB [00:00, 1.76MB/s]
A new version of the following files was downloaded from https://huggingface.co/microsoft/Phi-3-mini-128k-instruct:
- modeling_phi3.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
`flash-attention` package not found, consider installing for better performance: No module named 'flash_attn'.
Current `flash-attenton` does not support `window_size`. Either upgrade or use `attn_implementation='eager'`.
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████| 2/2 [00:04<00:00,  2.44s/it]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Running on local URL:  http://127.0.0.1:18888

To create a public link, set `share=True` in `launch()`.
Chat begin: generate an image of the fierce battle of warriors and the dragon
Chat end at 161.23 seconds: generate an image of the fierce battle of warriors and the dragon
100%|████████████████████████████████████████████████████████████████████████████████| 25/25 [01:01<00:00,  2.47s/it]
Chat begin: change the dragon to a dinosaur
Chat end at 361.10 seconds: change the dragon to a dinosaur
Last assistant response is not valid canvas: Response does not contain codes!

Pls help me to analyze the reasons for the confusion described above, thanks a lot.

**Comment by wikeeyang** [comment]
and I don't know why needto download Microsoft's original model's configure file? can I to change all "dtype=torch.floatxx" to "dtype=torch.float16" in the lib_omost\pipeline.py file?

**Comment by Yuhaoying** [comment]
w

**Comment by lllyasviel** [comment]
see also

https://github.com/lllyasviel/Omost/blob/bdf51c7a3944bb7dce60263023ac8d7a01c42b80/README.md?plain=1#L624

phi3 128k quant 8bit is somewhat less stable than llama3 8b 4bits when the token context is long enough

also phi3's 8 bit quant is similar size to llama3's 4bit quant so usually just use llama3

**Comment by wikeeyang** [comment]
Thanks a lot! I try llama3 8b 4bits is ok, but chat about 2 ir 3 rounds, due to token context is too long, GPU will out of memory.
