### ISSUE TITLE
Is there a version of comfyui?

### ISSUE THREAD

**Issue by Song367** [lllyasviel/Omost#42]

**Comment by mymusise** [comment]
Any guys going to do it?

**Comment by mymusise** [comment]
Found one, but it doesn't look like a completed version yet: https://github.com/huchenlei/ComfyUI_omost

**Comment by huchenlei** [comment]
> Found one, but it doesn't look like a completed version yet: https://github.com/huchenlei/ComfyUI_omost

You can already play around with it. I just added the complete ComfyUI area cond logic.

Still some TODOs though

**Comment by nanchen0076** [comment]
> > 找到了一个，但它看起来还不是完整的版本：https://github.com/huchenlei/ComfyUI_omost
> 
> 您已经可以尝试一下了。我刚刚添加了完整的 ComfyUI 区域条件逻辑。
> 
> 但还有一些待办事项

How does it compare?

**Comment by Song367** [comment]
> > 找到了一个，但它看起来还不是完整的版本：https://github.com/huchenlei/ComfyUI_omost
> 
> 您已经可以尝试一下了。我刚刚添加了完整的 ComfyUI 区域条件逻辑。
> 
> 但还有一些待办事项

**Comment by Song367** [comment]
> 找到了一个，但它看起来还不是完整的版本：https://github.com/huchenlei/ComfyUI_omost

OK
