### ISSUE TITLE
Which is better?

### ISSUE THREAD

**Issue by wodsoe** [lllyasviel/Omost#9]
omost-llama-3-8b
omost-dolphin-2.9-llama3-8b
omost-phi-3-mini-128k

Which is better?

**Comment by JPW0080** [comment]
Search for Model Notes 
https://github.com/lllyasviel/Omost

**Comment by lludlow** [comment]
see https://github.com/lllyasviel/Omost/blob/41fda3c01dbcf7ae7d238d4fa83718f4a425e581/README.md?plain=1#L603

`omost-llama-3-8b-4bits` > `omost-dolphin-2.9-llama3-8b-4bits` > `omost-phi-3-mini-128k-8bits`
